###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "Aplicativo",
    "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": [
        {"latitude": -27.751300},
        {"longitude":-48.633377},
        {"quartos": 3},
        {"cozinhas": 1},
        {"banheiros": 2},
        {"salas": 1},
        {"preco": 850}
    ]
}

# Aplicativo,tipo=casa01 latitude=-27.751300,longitude=-48.633377,quartos=3,cozinhas=1,banheiros=2,salas=1,preco=850

###

# Requisição inválida: cabeçalho não menciona formato
POST http://localhost:5000/gravar
Accept: application/json

{
    "medida": "Aplicativo",
    "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": [
        {"latitude": -27.751300},
        {"longitude":-48.633377},
        {"quartos": 3},
        {"cozinhas": 1},
        {"banheiros": 2},
        {"salas": 1},
        {"preco": 850}
    ]
}

###

# Requisição inválida: JSON com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "Aplicativo",
    "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": [
        {"latitude": -27.751300},
        {"longitude":-48.633377},
        {"quartos": 3},
        {"cozinhas": 1},
        {"banheiros": 2},
        {"salas": 1},
        {"preco": 850}
    ]

###

# Requisição inválida: falta 'medida'
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
     "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": [
        {"latitude": -27.751300},
        {"longitude":-48.633377},
        {"quartos": 3},
        {"cozinhas": 1},
        {"banheiros": 2},
        {"salas": 1},
        {"preco": 850}
    ]
}

###

# Requisição inválida: 'medida' com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": 120,
     "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": [
        {"latitude": -27.751300},
        {"longitude":-48.633377},
        {"quartos": 3},
        {"cozinhas": 1},
        {"banheiros": 2},
        {"salas": 1},
        {"preco": 850}
    ]
}

###

# Requisição inválida: falta 'valores'
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "Aplicativo",
    "marcadores": [
        {"tipo": "casa01"}
    ]
}

###

# Requisição inválida: 'valores' com formato errado
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "Aplicativo",
    "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": 4567
}

###

# Requisição inválida: lista 'valores' vazia
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "Aplicativo",
    "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": [
    ]
}

###

# Requisição válida
POST http://localhost:5000/gravar
Content-Type: application/json
Accept: application/json

{
    "medida": "Aplicativo",
    "marcadores": [
        {"tipo": "casa01"}
    ],
    "valores": [
        {"latitude": -27.751300},
        {"longitude":-48.633377},
        {"quartos": 3},
        {"cozinhas": 1},
        {"banheiros": 2},
        {"salas": 1},
        {"preco": 850}
    ]
}

###
